# Generated by Django 4.1 on 2022-09-03 20:12

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_mymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuillPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_quill.fields.QuillField()),
            ],
        ),
        migrations.DeleteModel(name="myModel",),
    ]
