# Generated by Django 4.1 on 2022-09-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0003_quillpost_delete_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(name="blogPost",),
    ]
