# Generated by Django 4.1 on 2022-09-03 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myblog", "0007_delete_blogpost"),
    ]

    operations = [
        migrations.RenameModel(old_name="QuillPost", new_name="blogPost",),
    ]
