# Generated by Django 4.1 on 2022-09-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0008_rename_quillpost_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="titletag",
            field=models.CharField(default="Blog Post", max_length=255),
        ),
    ]
